import manifest from "./downloads.json";

/**
 * What each sample ships, and where it lives in the bucket.
 *
 * `downloads.json` is generated by `scripts/samples/stage-packs.mjs`, which is
 * also what puts the objects in GCS — so the manifest cannot claim an asset the
 * bucket does not have. The exception is `full`, whose object stays null until
 * someone uploads the real delivery file; see the route for how that reads.
 */
export interface AssetEntry {
  object: string | null;
  bytes: number | null;
  filename: string;
  contentType: string;
  note?: string;
}

export type AssetKey = "preview" | "metadata" | "full";

/** Slug that means "the whole library" rather than one sample. */
export const FULL_SET_SLUG = "_set";

const M = manifest as unknown as {
  bucket: string | null;
  generatedAt: string;
  fullSet: (AssetEntry & { count: number }) | null;
  samples: Record<string, Record<AssetKey, AssetEntry>>;
};

export function assetFor(slug: string, asset: string): AssetEntry | null {
  if (slug === FULL_SET_SLUG) {
    return asset === "set" ? M.fullSet : null;
  }
  const entry = M.samples[slug];
  if (!entry) return null;
  if (asset !== "preview" && asset !== "metadata" && asset !== "full") return null;
  return entry[asset];
}

export function assetsFor(slug: string): Record<AssetKey, AssetEntry> | null {
  return M.samples[slug] ?? null;
}

export const fullSet = M.fullSet;

/** `1048576` -> `1.0 MB`. Null bytes mean the size is not known yet. */
export function humanBytes(bytes: number | null | undefined): string {
  if (bytes == null) return "size on request";
  if (bytes < 1024) return `${bytes} B`;
  const units = ["KB", "MB", "GB", "TB"];
  let value = bytes / 1024;
  let i = 0;
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024;
    i += 1;
  }
  return `${value < 10 ? value.toFixed(1) : Math.round(value)} ${units[i]}`;
}

export function downloadHref(slug: string, asset: AssetKey | "set"): string {
  return `/samples/api/download/${slug}/${asset}`;
}
