// AUTO-GENERATED by scripts/gen-gallery-static.mjs — do not edit by hand.
// Re-run as part of `pnpm build` or `pnpm dev`.

export type StaticImage = {
  path: string;
  name: string;
  ext: string;
  size_bytes: number;
};

export const STATIC_IMAGES: StaticImage[] = [
  {
    "path": "/images/2.png",
    "name": "2",
    "ext": "png",
    "size_bytes": 328445
  },
  {
    "path": "/images/3.png",
    "name": "3",
    "ext": "png",
    "size_bytes": 261403
  },
  {
    "path": "/images/ai-brain.jpg",
    "name": "ai-brain",
    "ext": "jpg",
    "size_bytes": 111746
  },
  {
    "path": "/images/automation-cinema-poster.jpg",
    "name": "automation-cinema-poster",
    "ext": "jpg",
    "size_bytes": 79810
  },
  {
    "path": "/images/avt-1.png",
    "name": "avt-1",
    "ext": "png",
    "size_bytes": 416804
  },
  {
    "path": "/images/avt-2.png",
    "name": "avt-2",
    "ext": "png",
    "size_bytes": 122248
  },
  {
    "path": "/images/avt-3.png",
    "name": "avt-3",
    "ext": "png",
    "size_bytes": 113303
  },
  {
    "path": "/images/avt-4.png",
    "name": "avt-4",
    "ext": "png",
    "size_bytes": 128914
  },
  {
    "path": "/images/avt-daviddo.png",
    "name": "avt-daviddo",
    "ext": "png",
    "size_bytes": 13583
  },
  {
    "path": "/images/avt-tamle.png",
    "name": "avt-tamle",
    "ext": "png",
    "size_bytes": 10948
  },
  {
    "path": "/images/bgr-ab.png",
    "name": "bgr-ab",
    "ext": "png",
    "size_bytes": 186316
  },
  {
    "path": "/images/blog-ai-future.jpg",
    "name": "blog-ai-future",
    "ext": "jpg",
    "size_bytes": 82926
  },
  {
    "path": "/images/blog-annotation.jpg",
    "name": "blog-annotation",
    "ext": "jpg",
    "size_bytes": 89916
  },
  {
    "path": "/images/blog-benchmark.jpg",
    "name": "blog-benchmark",
    "ext": "jpg",
    "size_bytes": 54612
  },
  {
    "path": "/images/blog-coding.jpg",
    "name": "blog-coding",
    "ext": "jpg",
    "size_bytes": 71599
  },
  {
    "path": "/images/blog-cybersecurity.jpg",
    "name": "blog-cybersecurity",
    "ext": "jpg",
    "size_bytes": 112045
  },
  {
    "path": "/images/blog-data-scale.jpg",
    "name": "blog-data-scale",
    "ext": "jpg",
    "size_bytes": 65082
  },
  {
    "path": "/images/blog-humanoid.jpg",
    "name": "blog-humanoid",
    "ext": "jpg",
    "size_bytes": 83297
  },
  {
    "path": "/images/blog-inline-code.jpg",
    "name": "blog-inline-code",
    "ext": "jpg",
    "size_bytes": 41629
  },
  {
    "path": "/images/blog-inline-lab.jpg",
    "name": "blog-inline-lab",
    "ext": "jpg",
    "size_bytes": 34044
  },
  {
    "path": "/images/blog-inline-medical.jpg",
    "name": "blog-inline-medical",
    "ext": "jpg",
    "size_bytes": 42418
  },
  {
    "path": "/images/blog-inline-pipeline.jpg",
    "name": "blog-inline-pipeline",
    "ext": "jpg",
    "size_bytes": 67967
  },
  {
    "path": "/images/blog-inline-robot-arm.jpg",
    "name": "blog-inline-robot-arm",
    "ext": "jpg",
    "size_bytes": 49807
  },
  {
    "path": "/images/blog-inline-team.jpg",
    "name": "blog-inline-team",
    "ext": "jpg",
    "size_bytes": 70905
  },
  {
    "path": "/images/blog-llm-training.jpg",
    "name": "blog-llm-training",
    "ext": "jpg",
    "size_bytes": 34603
  },
  {
    "path": "/images/blog-medical.jpg",
    "name": "blog-medical",
    "ext": "jpg",
    "size_bytes": 47323
  },
  {
    "path": "/images/blog-pipeline2.jpg",
    "name": "blog-pipeline2",
    "ext": "jpg",
    "size_bytes": 65370
  },
  {
    "path": "/images/blog-quality.jpg",
    "name": "blog-quality",
    "ext": "jpg",
    "size_bytes": 113442
  },
  {
    "path": "/images/blog-rlhf.jpg",
    "name": "blog-rlhf",
    "ext": "jpg",
    "size_bytes": 54087
  },
  {
    "path": "/images/blog-robotics-data.jpg",
    "name": "blog-robotics-data",
    "ext": "jpg",
    "size_bytes": 85695
  },
  {
    "path": "/images/blog-security.jpg",
    "name": "blog-security",
    "ext": "jpg",
    "size_bytes": 112045
  },
  {
    "path": "/images/blog-team-meeting.jpg",
    "name": "blog-team-meeting",
    "ext": "jpg",
    "size_bytes": 63882
  },
  {
    "path": "/images/blog-wp-breakthrough.jpg",
    "name": "blog-wp-breakthrough",
    "ext": "jpg",
    "size_bytes": 83297
  },
  {
    "path": "/images/blog-wp-data-running-out.jpg",
    "name": "blog-wp-data-running-out",
    "ext": "jpg",
    "size_bytes": 92958
  },
  {
    "path": "/images/blog-wp-slm.jpg",
    "name": "blog-wp-slm",
    "ext": "jpg",
    "size_bytes": 33889
  },
  {
    "path": "/images/body-kpts/arrange_fabric_t25.jpg",
    "name": "arrange_fabric_t25",
    "ext": "jpg",
    "size_bytes": 68936
  },
  {
    "path": "/images/body-kpts/arrange_fabric_t50.jpg",
    "name": "arrange_fabric_t50",
    "ext": "jpg",
    "size_bytes": 68056
  },
  {
    "path": "/images/body-kpts/arrange_fabric_t75.jpg",
    "name": "arrange_fabric_t75",
    "ext": "jpg",
    "size_bytes": 68219
  },
  {
    "path": "/images/body-kpts/iron_product_t25.jpg",
    "name": "iron_product_t25",
    "ext": "jpg",
    "size_bytes": 64978
  },
  {
    "path": "/images/body-kpts/iron_product_t50.jpg",
    "name": "iron_product_t50",
    "ext": "jpg",
    "size_bytes": 70441
  },
  {
    "path": "/images/body-kpts/iron_product_t75.jpg",
    "name": "iron_product_t75",
    "ext": "jpg",
    "size_bytes": 70435
  },
  {
    "path": "/images/body-kpts/pick_up_the_cup_t25.jpg",
    "name": "pick_up_the_cup_t25",
    "ext": "jpg",
    "size_bytes": 89169
  },
  {
    "path": "/images/body-kpts/pick_up_the_cup_t50.jpg",
    "name": "pick_up_the_cup_t50",
    "ext": "jpg",
    "size_bytes": 79572
  },
  {
    "path": "/images/body-kpts/pick_up_the_cup_t75.jpg",
    "name": "pick_up_the_cup_t75",
    "ext": "jpg",
    "size_bytes": 83864
  },
  {
    "path": "/images/body-kpts/sew_hem_t25.jpg",
    "name": "sew_hem_t25",
    "ext": "jpg",
    "size_bytes": 73334
  },
  {
    "path": "/images/body-kpts/sew_hem_t50.jpg",
    "name": "sew_hem_t50",
    "ext": "jpg",
    "size_bytes": 74492
  },
  {
    "path": "/images/body-kpts/sew_hem_t75.jpg",
    "name": "sew_hem_t75",
    "ext": "jpg",
    "size_bytes": 66869
  },
  {
    "path": "/images/code-screen.jpg",
    "name": "code-screen",
    "ext": "jpg",
    "size_bytes": 63915
  },
  {
    "path": "/images/data-dashboard.jpg",
    "name": "data-dashboard",
    "ext": "jpg",
    "size_bytes": 65370
  },
  {
    "path": "/images/datacenter-cinema-poster.jpg",
    "name": "datacenter-cinema-poster",
    "ext": "jpg",
    "size_bytes": 77862
  },
  {
    "path": "/images/deliverables/all6-montage.png",
    "name": "all6-montage",
    "ext": "png",
    "size_bytes": 388564
  },
  {
    "path": "/images/depth/pick_up_the_cup_rgb_depth.jpg",
    "name": "pick_up_the_cup_rgb_depth",
    "ext": "jpg",
    "size_bytes": 68957
  },
  {
    "path": "/images/descriptions/arrange_fabric.jpg",
    "name": "arrange_fabric",
    "ext": "jpg",
    "size_bytes": 78496
  },
  {
    "path": "/images/descriptions/iron_product.jpg",
    "name": "iron_product",
    "ext": "jpg",
    "size_bytes": 82666
  },
  {
    "path": "/images/descriptions/pick_up_the_cup.jpg",
    "name": "pick_up_the_cup",
    "ext": "jpg",
    "size_bytes": 129126
  },
  {
    "path": "/images/descriptions/sew_hem.jpg",
    "name": "sew_hem",
    "ext": "jpg",
    "size_bytes": 84518
  },
  {
    "path": "/images/diagrams/diagram-ladder.svg",
    "name": "diagram-ladder",
    "ext": "svg",
    "size_bytes": 3132
  },
  {
    "path": "/images/diagrams/diagram-pipeline.svg",
    "name": "diagram-pipeline",
    "ext": "svg",
    "size_bytes": 4787
  },
  {
    "path": "/images/diagrams/diagram-pricing.svg",
    "name": "diagram-pricing",
    "ext": "svg",
    "size_bytes": 3959
  },
  {
    "path": "/images/diagrams/diagram-qc.svg",
    "name": "diagram-qc",
    "ext": "svg",
    "size_bytes": 3004
  },
  {
    "path": "/images/env/dexterous-poster.jpg",
    "name": "dexterous-poster",
    "ext": "jpg",
    "size_bytes": 38107
  },
  {
    "path": "/images/env/dong_goi-poster.jpg",
    "name": "dong_goi-poster",
    "ext": "jpg",
    "size_bytes": 27013
  },
  {
    "path": "/images/env/electronics.jpg",
    "name": "electronics",
    "ext": "jpg",
    "size_bytes": 262439
  },
  {
    "path": "/images/env/gan_tag-poster.jpg",
    "name": "gan_tag-poster",
    "ext": "jpg",
    "size_bytes": 35316
  },
  {
    "path": "/images/env/hand.jpg",
    "name": "hand",
    "ext": "jpg",
    "size_bytes": 217092
  },
  {
    "path": "/images/env/in_ma_so-poster.jpg",
    "name": "in_ma_so-poster",
    "ext": "jpg",
    "size_bytes": 39797
  },
  {
    "path": "/images/env/is_san_pham-poster.jpg",
    "name": "is_san_pham-poster",
    "ext": "jpg",
    "size_bytes": 35010
  },
  {
    "path": "/images/env/kiem_tra_qc-poster.jpg",
    "name": "kiem_tra_qc-poster",
    "ext": "jpg",
    "size_bytes": 41086
  },
  {
    "path": "/images/env/kitchen.jpg",
    "name": "kitchen",
    "ext": "jpg",
    "size_bytes": 220615
  },
  {
    "path": "/images/env/may_san_pham-poster.jpg",
    "name": "may_san_pham-poster",
    "ext": "jpg",
    "size_bytes": 37674
  },
  {
    "path": "/images/env/pov.jpg",
    "name": "pov",
    "ext": "jpg",
    "size_bytes": 301656
  },
  {
    "path": "/images/env/sap_xep_vai-poster.jpg",
    "name": "sap_xep_vai-poster",
    "ext": "jpg",
    "size_bytes": 29179
  },
  {
    "path": "/images/env/sorting-poster.jpg",
    "name": "sorting-poster",
    "ext": "jpg",
    "size_bytes": 53743
  },
  {
    "path": "/images/env/sorting.jpg",
    "name": "sorting",
    "ext": "jpg",
    "size_bytes": 242948
  },
  {
    "path": "/images/env/textile.jpg",
    "name": "textile",
    "ext": "jpg",
    "size_bytes": 256461
  },
  {
    "path": "/images/env/warehouse-poster.jpg",
    "name": "warehouse-poster",
    "ext": "jpg",
    "size_bytes": 66712
  },
  {
    "path": "/images/env/warehouse.jpg",
    "name": "warehouse",
    "ext": "jpg",
    "size_bytes": 232580
  },
  {
    "path": "/images/facebook.png",
    "name": "facebook",
    "ext": "png",
    "size_bytes": 499
  },
  {
    "path": "/images/footnote.svg",
    "name": "footnote",
    "ext": "svg",
    "size_bytes": 10120682
  },
  {
    "path": "/images/hero-poster.jpg",
    "name": "hero-poster",
    "ext": "jpg",
    "size_bytes": 75432
  },
  {
    "path": "/images/hitl/annotated_sample.jpg",
    "name": "annotated_sample",
    "ext": "jpg",
    "size_bytes": 48902
  },
  {
    "path": "/images/hitl/hitl_capture_thumb.jpg",
    "name": "hitl_capture_thumb",
    "ext": "jpg",
    "size_bytes": 45856
  },
  {
    "path": "/images/hitl/hitl_clean_thumb.jpg",
    "name": "hitl_clean_thumb",
    "ext": "jpg",
    "size_bytes": 44284
  },
  {
    "path": "/images/hitl/hitl_wiping_thumb.jpg",
    "name": "hitl_wiping_thumb",
    "ext": "jpg",
    "size_bytes": 44139
  },
  {
    "path": "/images/hitl/preview_first.jpg",
    "name": "preview_first",
    "ext": "jpg",
    "size_bytes": 45856
  },
  {
    "path": "/images/hitl/preview_last.jpg",
    "name": "preview_last",
    "ext": "jpg",
    "size_bytes": 66620
  },
  {
    "path": "/images/hitl/preview_mid.jpg",
    "name": "preview_mid",
    "ext": "jpg",
    "size_bytes": 61491
  },
  {
    "path": "/images/hitl/reel_frame.png",
    "name": "reel_frame",
    "ext": "png",
    "size_bytes": 1680224
  },
  {
    "path": "/images/home-cinema-poster.jpg",
    "name": "home-cinema-poster",
    "ext": "jpg",
    "size_bytes": 90572
  },
  {
    "path": "/images/humanoid-ai.jpg",
    "name": "humanoid-ai",
    "ext": "jpg",
    "size_bytes": 234512
  },
  {
    "path": "/images/image.jpg",
    "name": "image",
    "ext": "jpg",
    "size_bytes": 450705
  },
  {
    "path": "/images/labeling.svg",
    "name": "labeling",
    "ext": "svg",
    "size_bytes": 2376412
  },
  {
    "path": "/images/linkedin.png",
    "name": "linkedin",
    "ext": "png",
    "size_bytes": 416
  },
  {
    "path": "/images/logo.svg",
    "name": "logo",
    "ext": "svg",
    "size_bytes": 6950198
  },
  {
    "path": "/images/mocap-studio.jpg",
    "name": "mocap-studio",
    "ext": "jpg",
    "size_bytes": 271106
  },
  {
    "path": "/images/modalities/exo-mocap.jpg",
    "name": "exo-mocap",
    "ext": "jpg",
    "size_bytes": 115529
  },
  {
    "path": "/images/modalities/mocap.jpg",
    "name": "mocap",
    "ext": "jpg",
    "size_bytes": 82961
  },
  {
    "path": "/images/modalities/qa.jpg",
    "name": "qa",
    "ext": "jpg",
    "size_bytes": 97203
  },
  {
    "path": "/images/modalities/spatial.jpg",
    "name": "spatial",
    "ext": "jpg",
    "size_bytes": 140534
  },
  {
    "path": "/images/modalities/teleop.jpg",
    "name": "teleop",
    "ext": "jpg",
    "size_bytes": 87969
  },
  {
    "path": "/images/modalities/umi.jpg",
    "name": "umi",
    "ext": "jpg",
    "size_bytes": 73281
  },
  {
    "path": "/images/office.png",
    "name": "office",
    "ext": "png",
    "size_bytes": 2439245
  },
  {
    "path": "/images/pack/hardware-pack.png",
    "name": "hardware-pack",
    "ext": "png",
    "size_bytes": 2234221
  },
  {
    "path": "/images/pack/operator-app.png",
    "name": "operator-app",
    "ext": "png",
    "size_bytes": 1694153
  },
  {
    "path": "/images/parts/headrig.jpg",
    "name": "headrig",
    "ext": "jpg",
    "size_bytes": 214962
  },
  {
    "path": "/images/physical-poster.jpg",
    "name": "physical-poster",
    "ext": "jpg",
    "size_bytes": 105202
  },
  {
    "path": "/images/platform-robotic-poster.jpg",
    "name": "platform-robotic-poster",
    "ext": "jpg",
    "size_bytes": 70378
  },
  {
    "path": "/images/platform/ai-providers.png",
    "name": "ai-providers",
    "ext": "png",
    "size_bytes": 123397
  },
  {
    "path": "/images/platform/batches-list.png",
    "name": "batches-list",
    "ext": "png",
    "size_bytes": 161505
  },
  {
    "path": "/images/platform/ctv-active-tasks.png",
    "name": "ctv-active-tasks",
    "ext": "png",
    "size_bytes": 210857
  },
  {
    "path": "/images/platform/dashboard.png",
    "name": "dashboard",
    "ext": "png",
    "size_bytes": 90455
  },
  {
    "path": "/images/platform/knowledge.png",
    "name": "knowledge",
    "ext": "png",
    "size_bytes": 127905
  },
  {
    "path": "/images/platform/project-overview.png",
    "name": "project-overview",
    "ext": "png",
    "size_bytes": 146927
  },
  {
    "path": "/images/platform/projects.png",
    "name": "projects",
    "ext": "png",
    "size_bytes": 102736
  },
  {
    "path": "/images/platform/team-directory.png",
    "name": "team-directory",
    "ext": "png",
    "size_bytes": 148458
  },
  {
    "path": "/images/post_banner.png",
    "name": "post_banner",
    "ext": "png",
    "size_bytes": 183194
  },
  {
    "path": "/images/post_bg.png",
    "name": "post_bg",
    "ext": "png",
    "size_bytes": 124145
  },
  {
    "path": "/images/post_card_bg.png",
    "name": "post_card_bg",
    "ext": "png",
    "size_bytes": 52839
  },
  {
    "path": "/images/public-datasets/ego4d.jpg",
    "name": "ego4d",
    "ext": "jpg",
    "size_bytes": 9379
  },
  {
    "path": "/images/public-datasets/egtea.jpg",
    "name": "egtea",
    "ext": "jpg",
    "size_bytes": 315
  },
  {
    "path": "/images/public-datasets/epic-kitchens.jpg",
    "name": "epic-kitchens",
    "ext": "jpg",
    "size_bytes": 9379
  },
  {
    "path": "/images/real-captures/clean_workstation__op_unknown__20260617T01.jpg",
    "name": "clean_workstation__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 44284
  },
  {
    "path": "/images/real-captures/clean_workstation_defect__op_unknown__20260617T01.jpg",
    "name": "clean_workstation_defect__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 49805
  },
  {
    "path": "/images/real-captures/clean_workstation_defect-loop.jpg",
    "name": "clean_workstation_defect-loop",
    "ext": "jpg",
    "size_bytes": 14306
  },
  {
    "path": "/images/real-captures/clean_workstation-loop.jpg",
    "name": "clean_workstation-loop",
    "ext": "jpg",
    "size_bytes": 19703
  },
  {
    "path": "/images/real-captures/cleaning_pantry_surface_defect__op_unknown__20260617T01.jpg",
    "name": "cleaning_pantry_surface_defect__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 166346
  },
  {
    "path": "/images/real-captures/cleaning_pantry_surface_defect-loop.jpg",
    "name": "cleaning_pantry_surface_defect-loop",
    "ext": "jpg",
    "size_bytes": 9093
  },
  {
    "path": "/images/real-captures/gan_tag_cho_san_pham__op_mobile__20260626T01.jpg",
    "name": "gan_tag_cho_san_pham__op_mobile__20260626T01",
    "ext": "jpg",
    "size_bytes": 216902
  },
  {
    "path": "/images/real-captures/gan_tag_cho_san_pham__op_mobile__20260626T02.jpg",
    "name": "gan_tag_cho_san_pham__op_mobile__20260626T02",
    "ext": "jpg",
    "size_bytes": 182237
  },
  {
    "path": "/images/real-captures/gan_tag_cho_san_pham__op_mobile__20260626T03.jpg",
    "name": "gan_tag_cho_san_pham__op_mobile__20260626T03",
    "ext": "jpg",
    "size_bytes": 160275
  },
  {
    "path": "/images/real-captures/gan_tag_cho_san_pham-loop.jpg",
    "name": "gan_tag_cho_san_pham-loop",
    "ext": "jpg",
    "size_bytes": 23985
  },
  {
    "path": "/images/real-captures/open_and_close_door__op_unknown__20260617T01.jpg",
    "name": "open_and_close_door__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 33242
  },
  {
    "path": "/images/real-captures/open_and_close_door-loop.jpg",
    "name": "open_and_close_door-loop",
    "ext": "jpg",
    "size_bytes": 9926
  },
  {
    "path": "/images/real-captures/pick_up_cup_defect__op_unknown__20260617T01.jpg",
    "name": "pick_up_cup_defect__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 49421
  },
  {
    "path": "/images/real-captures/pick_up_cup_defect-loop.jpg",
    "name": "pick_up_cup_defect-loop",
    "ext": "jpg",
    "size_bytes": 21423
  },
  {
    "path": "/images/real-captures/pick_up_item_from_fridge__op_unknown__20260617T01.jpg",
    "name": "pick_up_item_from_fridge__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 43801
  },
  {
    "path": "/images/real-captures/pick_up_item_from_fridge-loop.jpg",
    "name": "pick_up_item_from_fridge-loop",
    "ext": "jpg",
    "size_bytes": 17481
  },
  {
    "path": "/images/real-captures/pick_up_the_cup__op_anna__20260701T01.jpg",
    "name": "pick_up_the_cup__op_anna__20260701T01",
    "ext": "jpg",
    "size_bytes": 45856
  },
  {
    "path": "/images/real-captures/pick_up_the_cup__op_unknown__20260617T01.jpg",
    "name": "pick_up_the_cup__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 45856
  },
  {
    "path": "/images/real-captures/pick_up_the_cup-loop.jpg",
    "name": "pick_up_the_cup-loop",
    "ext": "jpg",
    "size_bytes": 20348
  },
  {
    "path": "/images/real-captures/smoke_test__op_smoke__20260701T01.jpg",
    "name": "smoke_test__op_smoke__20260701T01",
    "ext": "jpg",
    "size_bytes": 28384
  },
  {
    "path": "/images/real-captures/wiping_pantry_surface__op_unknown__20260617T01.jpg",
    "name": "wiping_pantry_surface__op_unknown__20260617T01",
    "ext": "jpg",
    "size_bytes": 44139
  },
  {
    "path": "/images/real-captures/wiping_pantry_surface-loop.jpg",
    "name": "wiping_pantry_surface-loop",
    "ext": "jpg",
    "size_bytes": 11195
  },
  {
    "path": "/images/real-samples/aloha.png",
    "name": "aloha",
    "ext": "png",
    "size_bytes": 108911
  },
  {
    "path": "/images/real-samples/mobile.png",
    "name": "mobile",
    "ext": "png",
    "size_bytes": 82340
  },
  {
    "path": "/images/real-samples/montage.png",
    "name": "montage",
    "ext": "png",
    "size_bytes": 388564
  },
  {
    "path": "/images/real-samples/openx.png",
    "name": "openx",
    "ext": "png",
    "size_bytes": 158522
  },
  {
    "path": "/images/real-samples/pusht.png",
    "name": "pusht",
    "ext": "png",
    "size_bytes": 35942
  },
  {
    "path": "/images/real-samples/sim.png",
    "name": "sim",
    "ext": "png",
    "size_bytes": 19790
  },
  {
    "path": "/images/real-samples/umi.png",
    "name": "umi",
    "ext": "png",
    "size_bytes": 156553
  },
  {
    "path": "/images/robot-hand.jpg",
    "name": "robot-hand",
    "ext": "jpg",
    "size_bytes": 67282
  },
  {
    "path": "/images/robotics-cinema-poster.jpg",
    "name": "robotics-cinema-poster",
    "ext": "jpg",
    "size_bytes": 34851
  },
  {
    "path": "/images/robotics-hero.jpg",
    "name": "robotics-hero",
    "ext": "jpg",
    "size_bytes": 50107
  },
  {
    "path": "/images/samples/cup.jpg",
    "name": "cup",
    "ext": "jpg",
    "size_bytes": 20569
  },
  {
    "path": "/images/samples/defect.jpg",
    "name": "defect",
    "ext": "jpg",
    "size_bytes": 19720
  },
  {
    "path": "/images/samples/door.jpg",
    "name": "door",
    "ext": "jpg",
    "size_bytes": 11105
  },
  {
    "path": "/images/samples/fridge.jpg",
    "name": "fridge",
    "ext": "jpg",
    "size_bytes": 18112
  },
  {
    "path": "/images/samples/wipe.jpg",
    "name": "wipe",
    "ext": "jpg",
    "size_bytes": 15435
  },
  {
    "path": "/images/samples/workstation.jpg",
    "name": "workstation",
    "ext": "jpg",
    "size_bytes": 17936
  },
  {
    "path": "/images/scientist-lab.jpg",
    "name": "scientist-lab",
    "ext": "jpg",
    "size_bytes": 106121
  },
  {
    "path": "/images/server-room.jpg",
    "name": "server-room",
    "ext": "jpg",
    "size_bytes": 89350
  },
  {
    "path": "/images/start3.png",
    "name": "start3",
    "ext": "png",
    "size_bytes": 11891
  },
  {
    "path": "/images/team-collab.jpg",
    "name": "team-collab",
    "ext": "jpg",
    "size_bytes": 77843
  },
  {
    "path": "/images/terminal-bench-cinema-poster.jpg",
    "name": "terminal-bench-cinema-poster",
    "ext": "jpg",
    "size_bytes": 68901
  },
  {
    "path": "/images/textile-annotated/arrange_01.jpg",
    "name": "arrange_01",
    "ext": "jpg",
    "size_bytes": 43363
  },
  {
    "path": "/images/textile-annotated/arrange_02.jpg",
    "name": "arrange_02",
    "ext": "jpg",
    "size_bytes": 47730
  },
  {
    "path": "/images/textile-annotated/iron_01.jpg",
    "name": "iron_01",
    "ext": "jpg",
    "size_bytes": 51033
  },
  {
    "path": "/images/textile-annotated/iron_02.jpg",
    "name": "iron_02",
    "ext": "jpg",
    "size_bytes": 46734
  },
  {
    "path": "/images/textile-annotated/package_01.jpg",
    "name": "package_01",
    "ext": "jpg",
    "size_bytes": 23568
  },
  {
    "path": "/images/textile-annotated/package_02.jpg",
    "name": "package_02",
    "ext": "jpg",
    "size_bytes": 46101
  },
  {
    "path": "/images/textile-annotated/print_01.jpg",
    "name": "print_01",
    "ext": "jpg",
    "size_bytes": 7605
  },
  {
    "path": "/images/textile-annotated/print_02.jpg",
    "name": "print_02",
    "ext": "jpg",
    "size_bytes": 38860
  },
  {
    "path": "/images/textile-annotated/quality_01.jpg",
    "name": "quality_01",
    "ext": "jpg",
    "size_bytes": 30327
  },
  {
    "path": "/images/textile-annotated/quality_02.jpg",
    "name": "quality_02",
    "ext": "jpg",
    "size_bytes": 90896
  },
  {
    "path": "/images/textile-annotated/sew_01.jpg",
    "name": "sew_01",
    "ext": "jpg",
    "size_bytes": 54510
  },
  {
    "path": "/images/textile-annotated/sew_02.jpg",
    "name": "sew_02",
    "ext": "jpg",
    "size_bytes": 42012
  },
  {
    "path": "/images/textile-raw/arrange_01.jpg",
    "name": "arrange_01",
    "ext": "jpg",
    "size_bytes": 43028
  },
  {
    "path": "/images/textile-raw/arrange_02.jpg",
    "name": "arrange_02",
    "ext": "jpg",
    "size_bytes": 37924
  },
  {
    "path": "/images/textile-raw/iron_01.jpg",
    "name": "iron_01",
    "ext": "jpg",
    "size_bytes": 38874
  },
  {
    "path": "/images/textile-raw/iron_02.jpg",
    "name": "iron_02",
    "ext": "jpg",
    "size_bytes": 44589
  },
  {
    "path": "/images/textile-raw/package_01.jpg",
    "name": "package_01",
    "ext": "jpg",
    "size_bytes": 23639
  },
  {
    "path": "/images/textile-raw/package_02.jpg",
    "name": "package_02",
    "ext": "jpg",
    "size_bytes": 39714
  },
  {
    "path": "/images/textile-raw/sew_01.jpg",
    "name": "sew_01",
    "ext": "jpg",
    "size_bytes": 39973
  },
  {
    "path": "/images/textile-raw/sew_02.jpg",
    "name": "sew_02",
    "ext": "jpg",
    "size_bytes": 42317
  },
  {
    "path": "/images/twitter.png",
    "name": "twitter",
    "ext": "png",
    "size_bytes": 488
  },
  {
    "path": "/images/worker-hero-poster.jpg",
    "name": "worker-hero-poster",
    "ext": "jpg",
    "size_bytes": 115436
  }
];
