// AUTO-GENERATED by scripts/gen-gallery-static.mjs — do not edit by hand.
// Re-run as part of `pnpm build` or `pnpm dev`.

export type StaticImage = {
  path: string;
  name: string;
  ext: string;
  size_bytes: number;
};

export const STATIC_IMAGES: StaticImage[] = [
  {
    "path": "/images/2.png",
    "name": "2",
    "ext": "png",
    "size_bytes": 328445
  },
  {
    "path": "/images/3.png",
    "name": "3",
    "ext": "png",
    "size_bytes": 261403
  },
  {
    "path": "/images/ai-brain.jpg",
    "name": "ai-brain",
    "ext": "jpg",
    "size_bytes": 111746
  },
  {
    "path": "/images/automation-cinema-poster.jpg",
    "name": "automation-cinema-poster",
    "ext": "jpg",
    "size_bytes": 79810
  },
  {
    "path": "/images/avt-1.png",
    "name": "avt-1",
    "ext": "png",
    "size_bytes": 416804
  },
  {
    "path": "/images/avt-2.png",
    "name": "avt-2",
    "ext": "png",
    "size_bytes": 122248
  },
  {
    "path": "/images/avt-3.png",
    "name": "avt-3",
    "ext": "png",
    "size_bytes": 113303
  },
  {
    "path": "/images/avt-4.png",
    "name": "avt-4",
    "ext": "png",
    "size_bytes": 128914
  },
  {
    "path": "/images/avt-daviddo.png",
    "name": "avt-daviddo",
    "ext": "png",
    "size_bytes": 13583
  },
  {
    "path": "/images/avt-tamle.png",
    "name": "avt-tamle",
    "ext": "png",
    "size_bytes": 10948
  },
  {
    "path": "/images/bgr-ab.png",
    "name": "bgr-ab",
    "ext": "png",
    "size_bytes": 186316
  },
  {
    "path": "/images/blog-ai-future.jpg",
    "name": "blog-ai-future",
    "ext": "jpg",
    "size_bytes": 82926
  },
  {
    "path": "/images/blog-annotation.jpg",
    "name": "blog-annotation",
    "ext": "jpg",
    "size_bytes": 89916
  },
  {
    "path": "/images/blog-benchmark.jpg",
    "name": "blog-benchmark",
    "ext": "jpg",
    "size_bytes": 54612
  },
  {
    "path": "/images/blog-coding.jpg",
    "name": "blog-coding",
    "ext": "jpg",
    "size_bytes": 71599
  },
  {
    "path": "/images/blog-cybersecurity.jpg",
    "name": "blog-cybersecurity",
    "ext": "jpg",
    "size_bytes": 112045
  },
  {
    "path": "/images/blog-data-scale.jpg",
    "name": "blog-data-scale",
    "ext": "jpg",
    "size_bytes": 65082
  },
  {
    "path": "/images/blog-humanoid.jpg",
    "name": "blog-humanoid",
    "ext": "jpg",
    "size_bytes": 83297
  },
  {
    "path": "/images/blog-inline-code.jpg",
    "name": "blog-inline-code",
    "ext": "jpg",
    "size_bytes": 41629
  },
  {
    "path": "/images/blog-inline-lab.jpg",
    "name": "blog-inline-lab",
    "ext": "jpg",
    "size_bytes": 34044
  },
  {
    "path": "/images/blog-inline-medical.jpg",
    "name": "blog-inline-medical",
    "ext": "jpg",
    "size_bytes": 42418
  },
  {
    "path": "/images/blog-inline-pipeline.jpg",
    "name": "blog-inline-pipeline",
    "ext": "jpg",
    "size_bytes": 67967
  },
  {
    "path": "/images/blog-inline-robot-arm.jpg",
    "name": "blog-inline-robot-arm",
    "ext": "jpg",
    "size_bytes": 49807
  },
  {
    "path": "/images/blog-inline-team.jpg",
    "name": "blog-inline-team",
    "ext": "jpg",
    "size_bytes": 70905
  },
  {
    "path": "/images/blog-llm-training.jpg",
    "name": "blog-llm-training",
    "ext": "jpg",
    "size_bytes": 34603
  },
  {
    "path": "/images/blog-medical.jpg",
    "name": "blog-medical",
    "ext": "jpg",
    "size_bytes": 47323
  },
  {
    "path": "/images/blog-pipeline2.jpg",
    "name": "blog-pipeline2",
    "ext": "jpg",
    "size_bytes": 65370
  },
  {
    "path": "/images/blog-quality.jpg",
    "name": "blog-quality",
    "ext": "jpg",
    "size_bytes": 113442
  },
  {
    "path": "/images/blog-rlhf.jpg",
    "name": "blog-rlhf",
    "ext": "jpg",
    "size_bytes": 54087
  },
  {
    "path": "/images/blog-robotics-data.jpg",
    "name": "blog-robotics-data",
    "ext": "jpg",
    "size_bytes": 85695
  },
  {
    "path": "/images/blog-security.jpg",
    "name": "blog-security",
    "ext": "jpg",
    "size_bytes": 112045
  },
  {
    "path": "/images/blog-team-meeting.jpg",
    "name": "blog-team-meeting",
    "ext": "jpg",
    "size_bytes": 63882
  },
  {
    "path": "/images/blog-wp-breakthrough.jpg",
    "name": "blog-wp-breakthrough",
    "ext": "jpg",
    "size_bytes": 83297
  },
  {
    "path": "/images/blog-wp-data-running-out.jpg",
    "name": "blog-wp-data-running-out",
    "ext": "jpg",
    "size_bytes": 92958
  },
  {
    "path": "/images/blog-wp-slm.jpg",
    "name": "blog-wp-slm",
    "ext": "jpg",
    "size_bytes": 33889
  },
  {
    "path": "/images/code-screen.jpg",
    "name": "code-screen",
    "ext": "jpg",
    "size_bytes": 63915
  },
  {
    "path": "/images/data-dashboard.jpg",
    "name": "data-dashboard",
    "ext": "jpg",
    "size_bytes": 65370
  },
  {
    "path": "/images/datacenter-cinema-poster.jpg",
    "name": "datacenter-cinema-poster",
    "ext": "jpg",
    "size_bytes": 77862
  },
  {
    "path": "/images/facebook.png",
    "name": "facebook",
    "ext": "png",
    "size_bytes": 499
  },
  {
    "path": "/images/footnote.svg",
    "name": "footnote",
    "ext": "svg",
    "size_bytes": 10120682
  },
  {
    "path": "/images/hero-poster.jpg",
    "name": "hero-poster",
    "ext": "jpg",
    "size_bytes": 75432
  },
  {
    "path": "/images/home-cinema-poster.jpg",
    "name": "home-cinema-poster",
    "ext": "jpg",
    "size_bytes": 90572
  },
  {
    "path": "/images/humanoid-ai.jpg",
    "name": "humanoid-ai",
    "ext": "jpg",
    "size_bytes": 234512
  },
  {
    "path": "/images/image.jpg",
    "name": "image",
    "ext": "jpg",
    "size_bytes": 450705
  },
  {
    "path": "/images/labeling.svg",
    "name": "labeling",
    "ext": "svg",
    "size_bytes": 2376412
  },
  {
    "path": "/images/linkedin.png",
    "name": "linkedin",
    "ext": "png",
    "size_bytes": 416
  },
  {
    "path": "/images/logo.svg",
    "name": "logo",
    "ext": "svg",
    "size_bytes": 6950198
  },
  {
    "path": "/images/mocap-studio.jpg",
    "name": "mocap-studio",
    "ext": "jpg",
    "size_bytes": 271106
  },
  {
    "path": "/images/office.png",
    "name": "office",
    "ext": "png",
    "size_bytes": 2439245
  },
  {
    "path": "/images/physical-poster.jpg",
    "name": "physical-poster",
    "ext": "jpg",
    "size_bytes": 105202
  },
  {
    "path": "/images/platform-robotic-poster.jpg",
    "name": "platform-robotic-poster",
    "ext": "jpg",
    "size_bytes": 70378
  },
  {
    "path": "/images/platform/ai-providers.png",
    "name": "ai-providers",
    "ext": "png",
    "size_bytes": 123397
  },
  {
    "path": "/images/platform/batches-list.png",
    "name": "batches-list",
    "ext": "png",
    "size_bytes": 172130
  },
  {
    "path": "/images/platform/ctv-active-tasks.png",
    "name": "ctv-active-tasks",
    "ext": "png",
    "size_bytes": 210857
  },
  {
    "path": "/images/platform/dashboard.png",
    "name": "dashboard",
    "ext": "png",
    "size_bytes": 88175
  },
  {
    "path": "/images/platform/knowledge.png",
    "name": "knowledge",
    "ext": "png",
    "size_bytes": 102794
  },
  {
    "path": "/images/platform/project-overview.png",
    "name": "project-overview",
    "ext": "png",
    "size_bytes": 143943
  },
  {
    "path": "/images/platform/projects.png",
    "name": "projects",
    "ext": "png",
    "size_bytes": 102736
  },
  {
    "path": "/images/platform/team-directory.png",
    "name": "team-directory",
    "ext": "png",
    "size_bytes": 148458
  },
  {
    "path": "/images/post_banner.png",
    "name": "post_banner",
    "ext": "png",
    "size_bytes": 183194
  },
  {
    "path": "/images/post_bg.png",
    "name": "post_bg",
    "ext": "png",
    "size_bytes": 124145
  },
  {
    "path": "/images/post_card_bg.png",
    "name": "post_card_bg",
    "ext": "png",
    "size_bytes": 52839
  },
  {
    "path": "/images/robot-hand.jpg",
    "name": "robot-hand",
    "ext": "jpg",
    "size_bytes": 67282
  },
  {
    "path": "/images/robotics-cinema-poster.jpg",
    "name": "robotics-cinema-poster",
    "ext": "jpg",
    "size_bytes": 34851
  },
  {
    "path": "/images/robotics-hero.jpg",
    "name": "robotics-hero",
    "ext": "jpg",
    "size_bytes": 50107
  },
  {
    "path": "/images/scientist-lab.jpg",
    "name": "scientist-lab",
    "ext": "jpg",
    "size_bytes": 106121
  },
  {
    "path": "/images/server-room.jpg",
    "name": "server-room",
    "ext": "jpg",
    "size_bytes": 89350
  },
  {
    "path": "/images/start3.png",
    "name": "start3",
    "ext": "png",
    "size_bytes": 11891
  },
  {
    "path": "/images/team-collab.jpg",
    "name": "team-collab",
    "ext": "jpg",
    "size_bytes": 77843
  },
  {
    "path": "/images/terminal-bench-cinema-poster.jpg",
    "name": "terminal-bench-cinema-poster",
    "ext": "jpg",
    "size_bytes": 68901
  },
  {
    "path": "/images/twitter.png",
    "name": "twitter",
    "ext": "png",
    "size_bytes": 488
  }
];
